In [1]:
#Programe:1 to rotate an array to left up to desire value
def fun(arr,n,k): 
  
    mod = k % n 
  
    for i in range(n): 
        print arr[(mod + i) % n], 
    
fun( arr=[ 1,2,3,4,5 ] ,n = len(arr) ,k= int(raw_input("enter a num:")))
  

    

  
    

NameError: name 'arr' is not defined

In [9]:
#1 what is difference between list and numpy array
import numpy as np
l=[1,2,3,4]
l1=[5,6,7,8]
sum_list=[i+j for i,j in zip(l,l1)]
ar1=np.array(l)
ar2=np.array(l1)
sum_array=ar1+ar2
#1- numpy array take less time to do any operation compare to list operation
# numpy array take time in ns and list take in micro second

In [10]:
print sum_list

[6, 8, 10, 12]


In [11]:
print sum_array

[ 6  8 10 12]


In [13]:
# one more functionalaty of numpy array is it has more function campare to list

In [14]:
import numpy as np
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [15]:
import numpy as np
np.array([1,2,3,'4'])

array(['1', '2', '3', '4'],
      dtype='|S11')

In [16]:
import numpy as np
np.array([1,2,3.0,5.4])

array([ 1. ,  2. ,  3. ,  5.4])

In [1]:
#so we can said that by using numpy array we can generte dynamic list like differnt dat type i.e str,float,copmlex no 
# but numpy array generate only homoginious list like same data type on top pyu can see them

In [7]:
i=1
res=[]
while i<2:
    i=i+.1
    res.append(i)
print res
    
    

[1.1, 1.2000000000000002, 1.3000000000000003, 1.4000000000000004, 1.5000000000000004, 1.6000000000000005, 1.7000000000000006, 1.8000000000000007, 1.9000000000000008, 2.000000000000001]


In [8]:
import numpy as np
i=1
res=[]
while i<2:
    i=i+.1
    res.append(i)
print np.res 

[1.1, 1.2000000000000002, 1.3000000000000003, 1.4000000000000004, 1.5000000000000004, 1.6000000000000005, 1.7000000000000006, 1.8000000000000007, 1.9000000000000008, 2.000000000000001]


AttributeError: 'module' object has no attribute 'res'

In [2]:
import numpy
print("Printing float range with numpy.arange()")
n=[]
for i in numpy.arange(0, 5.5, 0.5):
    n.append(i)
print (n)

Printing float range with numpy.arange()
[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]


In [1]:
# by using numpy module with arange we can print a list of float with desire interval

In [14]:
r=range(10)
for i in r:
    print(i)

SyntaxError: invalid syntax (<ipython-input-14-ad58bef4b166>, line 3)

In [16]:
import numpy as np
res=[]
for i in np.arange(1.5,8.5,0.5):
    res.append(i)
print (res)
    

[1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0]


In [17]:
#2:why should i used numpy in app development instead of list
#1 in numpy i have more function 
#2 by using numpy speed of my mathematical operation become fast
#3 by using numpy array i can generate dynamic list of any data tpye or if i repalce any index value of other data type it is 
# take only same data type or convert data type of complete list

In [18]:
#3: numpy array formation from list and tuple
import numpy as np
ar1=np.array([1,2,3,4,5,6,7,8,9])
ar1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
ar1.size

9

In [21]:
ar1.ndim

1

In [24]:
ar1.itemsize
# it gives the size of one element in byte i.e total size of array is
ar1.size*ar1.itemsize

36

In [27]:
#annother functinality is we can create n dimantion list by using array
ar1=np.array([0,1,2,3,4,5,6,7,8,9])
ar1.reshape(2,5)



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
# in reshape first one is come for how may dim and second is how many element
ar1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [31]:
# annnother thing is mathematical operation
ar1=np.array([1,2,3,4,5])
ar2=np.array([0,6,7,8,9])
ar1+ar2

array([ 1,  8, 10, 12, 14])

In [32]:
# annnother thing is mathematical operation
ar1=np.array([1,2,3,4,5])
ar2=np.array([0,6,7,8,9])
ar2-ar1

array([-1,  4,  4,  4,  4])

In [33]:
# annnother thing is mathematical operation
ar1=np.array([1,2,3,4,5])
ar2=np.array([0,6,7,8,9])
ar1*ar2

array([ 0, 12, 21, 32, 45])

In [35]:
# annnother thing is mathematical operation
ar1=np.array([1,2,3,4,5])
ar2=np.array([1,6,7,8,9])
ar1/ar2

array([1.        , 0.33333333, 0.42857143, 0.5       , 0.55555556])

In [36]:
#by using arange u can get a float no dynamic list
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [39]:
# but when you are looking for reshape of arange ,you have to know that how many elment in list so overcome by this problem 
# we use linspace
np.linspace(1,2,9)
# so third one is comes for how many element you want between 1 and 2 so u can reshape now

array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ])

In [42]:
ar4=np.linspace(1,27,9)
# most importent thing is u cant craet a new list by using linspace

In [43]:
# now u can reshape
np.linspace(1,2,9).reshape(3,3)
# so if u go for reshape then u have to use linspace instead of arange

array([[1.   , 1.125, 1.25 ],
       [1.375, 1.5  , 1.625],
       [1.75 , 1.875, 2.   ]])

In [45]:
# if u want to print random list with n dimentions then go with random.random
np.random.random((4,4))

array([[0.54750802, 0.39671308, 0.51514993, 0.13434854],
       [0.3052785 , 0.52365965, 0.22504853, 0.52453606],
       [0.26650282, 0.7349546 , 0.86992416, 0.25635535],
       [0.80458528, 0.74293489, 0.62426194, 0.18851948]])

In [46]:
# same data type array can do operation and float and int also do the opertion but different data type like str(|S6) and 
# int does not support operation
# 3: mathematical operations in array that is discussed

In [47]:
#4: sliciing different between list and np array slicing
l1=[1,2,3,4,5]
l2=[5,6,4,8,9]
l1[0]

1

In [50]:
l1=[1,2,3,4,5]
l2=[5,6,4,8,9]
l1[0]=10
l1


[10, 2, 3, 4, 5]

In [57]:
l1=[1,2,3,4,5]
l2=[5,6,4,8,9]
l2=l1
l2[0]=10
l1

[10, 2, 3, 4, 5]

In [52]:
l1=[1,2,3,4,5]
l2=[5,6,4,8,9]
l2[0]=20
l1
# u can see in this if u go to changes in l2 then l1 is not affeced bcz they both have saparate memory location

[1, 2, 3, 4, 5]

In [55]:
ar1=np.array(arange(5))
ar2=np.array(arange(5,9,1))
ar2[0]=10
print (ar2)

NameError: name 'arange' is not defined

In [66]:
# sum of rows and colons and whole element of array
ar1=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])
ar1.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
# sum of total element of ar1
ar1.sum()

105

In [78]:
#sum of the rows of ar1 after reshape
ar1=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])
ar1.reshape(3,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [79]:
#sum of the rows of ar1 after reshape
ar1=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])
ar1.reshape(3,5).sum(axis=1)

array([10, 35, 60])

In [80]:
#sum of the coloms of ar1 after reshape
ar1=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])
ar1.reshape(3,5).sum(axis=0)

array([15, 18, 21, 24, 27])

In [2]:
# T is use for transpose i.e. swap rows to colon and colon to rows during reshape


SyntaxError: invalid syntax (<ipython-input-2-ac648802ba8f>, line 2)

import numpy as  np


In [7]:
import numpy as np
ar1=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])
ar1.reshape(3,5).T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [8]:
# by using t you can tranpose of your reshape

In [10]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
ar1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr=ar1.reshape(3,3)